import { AuthContextProvider } from '@/src/context/AuthContext';
import './globals.css';
import SideBar from './components/SideBar/SideBar';
import RouteHandler from '@/src/hooks/RouteHandler';

import { montserrat } from '@/src/font';

export const metadata = {
  title: 'Aether Trials',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <AuthContextProvider>
          <div className='sidebarWrapper'>
            <SideBar />
          </div>
          <div className='contentWrapper'>
            {/* <RouteHandler /> */}
            {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
