import { AuthContextProvider } from '@/src/context/AuthContext';
import './globals.css';
import { Roboto } from 'next/font/google';
import SideBar from './components/SideBar/SideBar';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Proyecto Trials',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <AuthContextProvider>
          <div className='sidebarWrapper'>
            <SideBar />
          </div>
          <div className='contentWrapper'>{children}</div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
